services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - connectPerso

  nginx:
    image: nginx:stable
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
      - ./ngninx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - connectPerso

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cour
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - connectPerso
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - connectPerso

networks:
  connectPerso:
    driver: bridge

volumes:
  mysql_data:
